// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8eSgV9WHPR6K_hRxc04Mp_RMAZMoeqrI',
    appId: '1:340943489994:web:9af464a78f03dbbab19d33',
    messagingSenderId: '340943489994',
    projectId: 'flutterfirebaseapp-9f04c',
    authDomain: 'flutterfirebaseapp-9f04c.firebaseapp.com',
    storageBucket: 'flutterfirebaseapp-9f04c.appspot.com',
    measurementId: 'G-0ZRZXQ83HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0CuRw5rqYxpSDXQmH-ppXDvctwYroRRw',
    appId: '1:340943489994:android:905339ffd1915c83b19d33',
    messagingSenderId: '340943489994',
    projectId: 'flutterfirebaseapp-9f04c',
    storageBucket: 'flutterfirebaseapp-9f04c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcO9RB37r6lG1291RibzX4WUvpBLmSPD4',
    appId: '1:340943489994:ios:fea4393557d3b07ab19d33',
    messagingSenderId: '340943489994',
    projectId: 'flutterfirebaseapp-9f04c',
    storageBucket: 'flutterfirebaseapp-9f04c.appspot.com',
    iosBundleId: 'com.example.flutterfirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcO9RB37r6lG1291RibzX4WUvpBLmSPD4',
    appId: '1:340943489994:ios:e9e87fe2ef1cab4eb19d33',
    messagingSenderId: '340943489994',
    projectId: 'flutterfirebaseapp-9f04c',
    storageBucket: 'flutterfirebaseapp-9f04c.appspot.com',
    iosBundleId: 'com.example.flutterfirebaseapp.RunnerTests',
  );
}
